// const os = require("os");


//   const systemInfo = {
//       hostname: os.hostname(),
//       platform: os.platform(),
//       type: os.type(),
//       release: os.release(),
//       uptime: os.uptime(),
//       loadavg: os.loadavg(),
//       totalmem: os.totalmem(),
//       freemem: os.freemem(),
//       cpus: os.cpus(),
//       networkInterfaces: os.networkInterfaces(),
//       userInfo: os.userInfo(),
//       arch: os.arch(),
//       tmpdir: os.tmpdir(),
//       homedir: os.homedir(),
//       endianness: os.endianness(),
//       EOL: os.EOL,
//       "os.devNull": os.devNull,
//       "Home Directory": os.homedir(),
//       "Operating System": os.type(),
//       "Last Reboot": os.uptime(),
//       "Total Memory": os.totalmem(),
//       "Free Memory": os.freemem(),
//       "CPU Count": os.cpus().length,
//       "CPU Model": os.cpus()[0].model,
//       "CPU Speed": os.cpus()[0].speed,
//       "Network Interfaces": os.networkInterfaces(),
//       Version: os.version(),
//       Release: os.release(),
//       Architecture: os.arch(),
//       Platform: os.platform(),
//       Hostname: os.hostname(),
//       Endianness: os.endianness(),
//       "process.platform": process.platform === "win32" ? "\r," : " " + " ", // Windows uses \r for newlines, so we need to replace it with \r,
//       "process.arch": process.arch,
//       "process.cwd()": process.cwd(),
//       "process.execPath": process.execPath,
//       "process.features": process.features,
//       "process.uptime()": process.uptime().toFixed(2),
//       "process.memoryUsage()":
//         `${process.memoryUsage().heapUsed / 1024 / 1024} MB`,
//       "process.cpuUsage()": process.cpuUsage().user.toFixed(2),
//       "process.cpuUsage().system": process.cpuUsage().system.toFixed(2),
//       "process.hrtime()": process.hrtime(),
//       "process.hrtime.bigint()": process.hrtime.bigint(),
//       "process.config": process.config,
//       "process.title": process.title,
//       "process.version": process.version,
//       "process.versions": process.versions,
//       "process.release": process.release,
//       "process.versions.node": process.versions.node,
//       "process.versions.v8": process.versions.v8,

//   };
// module.exports = systemInfo;

      // "process.stdout": process.stdout,
      // "process.stderr": process.stderr,
      // "process.stdin": process.stdin,
     // "process.env": process.env,
      // "process.argv": process.argv,
      // "process.execArgv": process.execArgv,
       // "process.allowedNodeEnvironmentFlags": process.allowedNodeEnvironmentFlags,
      // "process.report": process.report,
      // "process.versions.uv": process.versions.uv,
      // "process.versions.zlib": process.versions.zlib,
      // "process.versions.brotli": process.versions.brotli,
      // "process.versions.ares": process.versions.ares,
      // "process.versions.modules": process.versions.modules,
      // "process.versions.nghttp2": process.versions.nghttp2,
      // "process.versions.napi": process.versions.napi,
      // "process.versions.llhttp": process.versions.llhttp,
      // "process.versions.http_parser": process.versions.http_parser,
      // "process.versions.openssl": process.versions.openssl,
      // "process.versions.cldr": process.versions.cldr,
      // "process.versions.icu": process.versions.icu,
      // "process.versions.tz": process.versions.tz,
      // "process.versions.unicode": process.versions.unicode,
      // "os.devNull": os.devNull,
      // "os.constants": os.constants,
      // "os.constants.signals": os.constants.signals,
      // "os.constants.errno": os.constants.errno,
      // "os.constants.priority": os.constants.priority,
      // "os.constants.dlopen": os.constants.dlopen,
      // "os.constants.fs": os.constants.fs,
      // "os.constants.os": os.constants.os,
      // "os.constants.sched": os.constants.sched